const START_GAME = 'START_GAME';
const OPEN_CELL = 'OPEN_CELL';
const CLICK_MINE = 'CLICK_MINE';
const TO_FLAG_CELL = 'TO_FLAG_CELL';
const TO_QUESTION_CELL = 'TO_QUESTION_CELL';
const NORMALIZE_CELL = 'NORMALIZE_CELL';
const INCREMENT_TIMER = 'INCREMENT_TIMER';

const CODE = {
  MINE: -7,
  NORMAL: -1,
  QUESTION: -2,
  FLAG: -3,
  QUESTION_MINE: -4,
  FLAG_MINE: -5,
  CLICKED_MINE: -6,
  OPENED: 0 // 0 이상이면 다 opened
}

module.exports = {
  START_GAME,
  OPEN_CELL,
  CLICK_MINE,
  CODE,
  TO_FLAG_CELL,
  TO_QUESTION_CELL,
  NORMALIZE_CELL
}